services:
  client:
    build:
      context: ./client
      target: production
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      target: production
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
      - NODE_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
